import { Post, Story, Destination } from './types';

export const ALL_DESTINATIONS: Destination[] = [
  // ==========================================
  // REGIÓN COSTA
  // ==========================================
  
  // --- MANABÍ ---
  {
    id: 'c_machalilla',
    name: 'Parque Nacional Machalilla',
    location: 'Puerto López',
    region: 'Costa',
    province: 'Manabí',
    description: 'Santuario de naturaleza y arqueología.',
    fullDescription: 'El área protegida más importante de la costa. Bosques secos, playas vírgenes y sitios arqueológicos de la cultura Manteña.',
    imageUrl: 'https://images.unsplash.com/photo-1598384232375-a010488950d4?q=80&w=800&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1620668045956-6511b8b21245?q=80&w=800&auto=format&fit=crop'],
    highlights: ['Los Frailes', 'Isla de la Plata', 'Agua Blanca'],
    travelTips: ['Lleva agua', 'Usa sombrero', 'No dejes basura'],
    category: 'Naturaleza',
    rating: 5.0
  },
  {
    id: 'c_frailes',
    name: 'Playa Los Frailes',
    location: 'Puerto López',
    region: 'Costa',
    province: 'Manabí',
    description: 'La playa más limpia del Ecuador.',
    fullDescription: 'Una playa de arena blanca perfecta, protegida del ruido y la contaminación. Ideal para relajarse y hacer senderismo.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Mirador', 'Senderos', 'Snorkel'],
    travelTips: ['Cierra 16:00', 'Sin tiendas', 'Lleva tomatodo'],
    category: 'Playa',
    rating: 5.0
  },
  {
    id: 'c_puertolopez',
    name: 'Puerto López',
    location: 'Puerto López',
    region: 'Costa',
    province: 'Manabí',
    description: 'Capital de las ballenas jorobadas.',
    fullDescription: 'Pueblo pesquero vibrante, base para tours de observación de ballenas (Jun-Sep) y vida nocturna relajada.',
    imageUrl: 'https://images.unsplash.com/photo-1589990372204-7667232230a3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Ballenas', 'Muelle', 'Mercado'],
    travelTips: ['Come mariscos', 'Toma mototaxi', 'Madruga'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 'c_manta',
    name: 'Playa Murciélago',
    location: 'Manta',
    region: 'Costa',
    province: 'Manabí',
    description: 'Playa urbana moderna y vibrante.',
    fullDescription: 'El corazón turístico de Manta. Malecón escénico, restaurantes de lujo y deportes acuáticos.',
    imageUrl: 'https://images.unsplash.com/photo-1622312270830-22c507117188?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Malecón', 'Kitesurf', 'Gastronomía'],
    travelTips: ['Visita el Mall', 'Come en el malecón', 'Usa bloqueador'],
    category: 'Playa',
    rating: 4.7
  },
  {
    id: 'c_canoa',
    name: 'Canoa',
    location: 'San Vicente',
    region: 'Costa',
    province: 'Manabí',
    description: 'Playa extensa para surf y parapente.',
    fullDescription: 'Destino relajado con kilómetros de playa, cuevas y acantilados ideales para volar.',
    imageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Parapente', 'Surf', 'Cuevas'],
    travelTips: ['Vuela al atardecer', 'Prueba corviches', 'Fiesta en la playa'],
    category: 'Aventura',
    rating: 4.7
  },
  {
    id: 'c_san_lorenzo',
    name: 'Cabo San Lorenzo',
    location: 'Manta',
    region: 'Costa',
    province: 'Manabí',
    description: 'El punto más saliente de Ecuador.',
    fullDescription: 'Hogar del faro de San Lorenzo y zona de anidación de tortugas marinas. Paisajes de acantilados.',
    imageUrl: 'https://images.unsplash.com/photo-1565625350410-b99b642e4636?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Faro', 'Tortugas', 'Senderos'],
    travelTips: ['Sube al faro', 'Lleva cámara', 'Respeta nidos'],
    category: 'Naturaleza',
    rating: 4.6
  },
  {
    id: 'c_pacoche',
    name: 'Refugio Pacoche',
    location: 'Manta',
    region: 'Costa',
    province: 'Manabí',
    description: 'Selva húmeda junto al mar.',
    fullDescription: 'Un bosque húmedo increíble en medio de zona seca. Hogar de monos aulladores y gran biodiversidad.',
    imageUrl: 'https://images.unsplash.com/photo-1548232979-6c557ee14752?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Monos aulladores', 'Sendero', 'Naturaleza'],
    travelTips: ['Contrata guía', 'Haz silencio', 'Usa repelente'],
    category: 'Naturaleza',
    rating: 4.7
  },
  {
    id: 'c_santa_marianita',
    name: 'Santa Marianita',
    location: 'Manta',
    region: 'Costa',
    province: 'Manabí',
    description: 'Capital del Kitesurf.',
    fullDescription: 'Playa ventosa ideal para deportes de viento. Ambiente joven y deportivo.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Kitesurf', 'Atardeceres', 'Relax'],
    travelTips: ['Toma clases', 'Mucho viento', 'Lleva abrigo ligero'],
    category: 'Aventura',
    rating: 4.5
  },
  {
    id: 'c_cojimies',
    name: 'Cojimíes',
    location: 'Pedernales',
    region: 'Costa',
    province: 'Manabí',
    description: 'Tierra de palmeras y estuarios.',
    fullDescription: 'Playa rodeada de miles de cocoteros. Acceso a la Isla del Amor en el estuario.',
    imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Isla del Amor', 'Palmeras', 'Comida'],
    travelTips: ['Cruza en lancha', 'Come encocado', 'Playa tranquila'],
    category: 'Playa',
    rating: 4.4
  },
  {
    id: 'c_bahia',
    name: 'Bahía de Caráquez',
    location: 'Sucre',
    region: 'Costa',
    province: 'Manabí',
    description: 'Eco-ciudad patrimonial.',
    fullDescription: 'Ciudad tranquila en una península. Cruzando el puente más largo del país.',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Puente', 'Museo', 'Mirador'],
    travelTips: ['Cruza caminando', 'Visita Chirije', 'Ambiente familiar'],
    category: 'Cultura',
    rating: 4.6
  },
  {
    id: 'c_crucita',
    name: 'Crucita',
    location: 'Portoviejo',
    region: 'Costa',
    province: 'Manabí',
    description: 'La Bella de Manabí.',
    fullDescription: 'Famosa por el vuelo en parapente desde la loma y su gastronomía.',
    imageUrl: 'https://images.unsplash.com/photo-1605218427368-35b86d9a978f?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Parapente', 'Playa', 'Viche'],
    travelTips: ['Vuela', 'Come viche', 'Disfruta la vista'],
    category: 'Aventura',
    rating: 4.6
  },
  {
    id: 'c_ayampe',
    name: 'Ayampe',
    location: 'Puerto López',
    region: 'Costa',
    province: 'Manabí',
    description: 'Selva y mar en armonía.',
    fullDescription: 'Pueblo tranquilo, calles de tierra, mucha vegetación y surf. Ambiente yoga y relax.',
    imageUrl: 'https://images.unsplash.com/photo-1473116763249-56381a35022f?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Surf', 'Yoga', 'Atardecer'],
    travelTips: ['Desconéctate', 'Prueba comida vegana', 'Observa aves'],
    category: 'Playa',
    rating: 4.8
  },
  {
    id: 'c_san_mateo',
    name: 'Puerto de San Mateo',
    location: 'Manta',
    region: 'Costa',
    province: 'Manabí',
    description: 'Puerto pesquero artesanal.',
    fullDescription: 'Un puerto renovado con una playa tranquila y excelente vista de Manta.',
    imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Pesca', 'Playa', 'Mirador'],
    travelTips: ['Compra pescado fresco', 'Camina el muelle', 'Playa segura'],
    category: 'Cultura',
    rating: 4.3
  },
  {
    id: 'c_agua_blanca',
    name: 'Comuna Agua Blanca',
    location: 'Puerto López',
    region: 'Costa',
    province: 'Manabí',
    description: 'Laguna de azufre y arqueología.',
    fullDescription: 'Comunidad ancestral dentro del parque Machalilla. Museo y laguna medicinal.',
    imageUrl: 'https://images.unsplash.com/photo-1589391090333-e77373809b02?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Laguna sulfurosa', 'Museo', 'Bosque seco'],
    travelTips: ['Báñate en lodo', 'Apoya a la comunidad', 'Senderismo'],
    category: 'Cultura',
    rating: 4.7
  },
  {
    id: 'c_isla_corazon',
    name: 'Isla Corazón',
    location: 'San Vicente',
    region: 'Costa',
    province: 'Manabí',
    description: 'Túneles de manglar con forma de corazón.',
    fullDescription: 'Refugio de vida silvestre en el estuario del río Chone. Colonia de fragatas.',
    imageUrl: 'https://images.unsplash.com/photo-1543152042-429380798eb3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Manglares', 'Fragatas', 'Canoa'],
    travelTips: ['Tour en canoa', 'Avistamiento de aves', 'Lleva repelente'],
    category: 'Naturaleza',
    rating: 4.6
  },

  // --- SANTA ELENA ---
  {
    id: 'c_montanita',
    name: 'Montañita',
    location: 'Santa Elena',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Surf y fiesta internacional.',
    fullDescription: 'Pueblo bohemio famoso mundialmente por sus olas y vida nocturna.',
    imageUrl: 'https://images.unsplash.com/photo-1533230588647-73d745c9938c?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Surf', 'Fiesta', 'Playa'],
    travelTips: ['Cuidado corrientes', 'Prueba cocteles', 'Disfruta la noche'],
    category: 'Aventura',
    rating: 4.7
  },
  {
    id: 'c_salinas',
    name: 'Salinas',
    location: 'Salinas',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Balneario moderno con edificios.',
    fullDescription: 'Ciudad costera con infraestructura hotelera, yates y la Chocolatera.',
    imageUrl: 'https://images.unsplash.com/photo-1596229777598-a83cb3f0e071?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Chocolatera', 'San Lorenzo', 'Yates'],
    travelTips: ['Visita la Lobería', 'Motos acuáticas', 'Paseo malecón'],
    category: 'Playa',
    rating: 4.8
  },
  {
    id: 'c_ayangue',
    name: 'Ayangue',
    location: 'Santa Elena',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Piscina del Pacífico.',
    fullDescription: 'Bahía cerrada de aguas mansas, ideal para niños y buceo.',
    imageUrl: 'https://images.unsplash.com/photo-1616422209562-b7d60233475d?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Buceo', 'Langosta', 'Playa mansa'],
    travelTips: ['Come mariscos', 'Snorkel', 'Playa familiar'],
    category: 'Playa',
    rating: 4.6
  },
  {
    id: 'c_olon',
    name: 'Olón',
    location: 'Santa Elena',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Tranquilidad junto a Montañita.',
    fullDescription: 'Playa extensa y tranquila, con el santuario en el acantilado.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Santuario', 'Playa ancha', 'Cascadas'],
    travelTips: ['Sube al santuario', 'Camina la playa', 'Relax'],
    category: 'Playa',
    rating: 4.7
  },
  {
    id: 'c_chocolatera',
    name: 'La Chocolatera',
    location: 'Salinas',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Punto más saliente del Ecuador.',
    fullDescription: 'Reserva marina donde el mar choca con fuerza. Lobería y faro.',
    imageUrl: 'https://images.unsplash.com/photo-1550614000-4b9519e4876a?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Lobería', 'Faro', 'Olas'],
    travelTips: ['No bañarse', 'Mucho viento', 'Fotos increíbles'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 'c_anconcito',
    name: 'Anconcito',
    location: 'Salinas',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Puerto pesquero pintoresco.',
    fullDescription: 'Pueblo de pescadores con vistas panorámicas desde los acantilados.',
    imageUrl: 'https://images.unsplash.com/photo-1534234828569-2c75a40733d0?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Puerto', 'Acantilados', 'Pesca'],
    travelTips: ['Visita el puerto', 'Compra pescado', 'Vistas'],
    category: 'Cultura',
    rating: 4.3
  },
  {
    id: 'c_dos_mangas',
    name: 'Comuna Dos Mangas',
    location: 'Manglaralto',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Senderismo y cascadas.',
    fullDescription: 'Turismo comunitario en la cordillera Chongón-Colonche. Bosque húmedo.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cascadas', 'Artesanías', 'Senderos'],
    travelTips: ['Alquila bici', 'Lleva repelente', 'Compra paja toquilla'],
    category: 'Aventura',
    rating: 4.5
  },
  {
    id: 'c_punta_carnero',
    name: 'Punta Carnero',
    location: 'Salinas',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Playa salvaje para surf.',
    fullDescription: 'Playa de mar abierto con oleaje fuerte, escenario de mundiales de surf.',
    imageUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Surf', 'Atardecer', 'Tranquilidad'],
    travelTips: ['Peligroso nadar', 'Fotos atardecer', 'Caminata'],
    category: 'Playa',
    rating: 4.4
  },
  {
    id: 'c_libertador',
    name: 'Libertador Bolívar',
    location: 'Santa Elena',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Artesanías y playa.',
    fullDescription: 'Pueblo conocido por sus hamacas y artesanías en paja y tagua frente al mar.',
    imageUrl: 'https://images.unsplash.com/photo-1612293905560-61853db5448b?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Artesanías', 'Playa', 'Gastronomía'],
    travelTips: ['Compra hamaca', 'Come mariscos', 'Visita talleres'],
    category: 'Cultura',
    rating: 4.4
  },
  {
    id: 'c_ballenita',
    name: 'Ballenita',
    location: 'Santa Elena',
    region: 'Costa',
    province: 'Santa Elena',
    description: 'Mirador natural.',
    fullDescription: 'Playa tranquila con un mirador desde donde a veces se ven ballenas.',
    imageUrl: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c78?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Mirador', 'Museo Náutico', 'Playa'],
    travelTips: ['Visita Farallón Dillon', 'Relájate', 'Comida local'],
    category: 'Playa',
    rating: 4.3
  },

  // --- ESMERALDAS ---
  {
    id: 'c_mompiche',
    name: 'Mompiche',
    location: 'Muisne',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'Paraíso tropical del surf.',
    fullDescription: 'Playa de arena oscura, selva y una de las mejores olas de izquierda del Pacífico.',
    imageUrl: 'https://images.unsplash.com/photo-1544642296-123f9b28291b?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Surf', 'Playa Negra', 'Selva'],
    travelTips: ['Clases surf', 'Playa Negra cerca', 'Ambiente rústico'],
    category: 'Playa',
    rating: 4.8
  },
  {
    id: 'c_atacames',
    name: 'Atacames',
    location: 'Atacames',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'La playa de la fiesta eterna.',
    fullDescription: 'El balneario más popular del norte. Bares en la playa, música y mucha gente.',
    imageUrl: 'https://images.unsplash.com/photo-1596489397685-6e0a8118029d?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Caipiriñas', 'Vida nocturna', 'Peñón'],
    travelTips: ['Prueba coco', 'Fiesta noche', 'Cuidado seguridad'],
    category: 'Playa',
    rating: 4.3
  },
  {
    id: 'c_sua',
    name: 'Súa',
    location: 'Atacames',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'Piscina natural tranquila.',
    fullDescription: 'Bahía calma vecina a Atacames. Ideal para nadar y ver aves marinas.',
    imageUrl: 'https://images.unsplash.com/photo-1621376822209-482869927771?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Isla Pájaros', 'Piqueros', 'Calma'],
    travelTips: ['Paseo lancha', 'Ver aves', 'Ideal niños'],
    category: 'Naturaleza',
    rating: 4.4
  },
  {
    id: 'c_same',
    name: 'Same',
    location: 'Esmeraldas',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'Exclusividad y estilo mediterráneo.',
    fullDescription: 'Playa rodeada de colinas y condominios blancos estilo Casablanca.',
    imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Casablanca', 'Playa privada', 'Lujo'],
    travelTips: ['Alquila depa', 'Playa limpia', 'Relax total'],
    category: 'Playa',
    rating: 4.7
  },
  {
    id: 'c_las_palmas',
    name: 'Las Palmas',
    location: 'Esmeraldas',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'Malecón regenerado de la ciudad.',
    fullDescription: 'Playa urbana de Esmeraldas con un malecón moderno, restaurantes y zonas deportivas.',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Malecón', 'Deportes', 'Comida'],
    travelTips: ['Prueba encocado', 'Paseo tarde', 'Seguridad mejorada'],
    category: 'Playa',
    rating: 4.2
  },
  {
    id: 'c_tonchigue',
    name: 'Tonchigüe',
    location: 'Atacames',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'Pueblo pesquero auténtico.',
    fullDescription: 'Pequeño puerto pesquero con playa tranquila y mariscos frescos.',
    imageUrl: 'https://images.unsplash.com/photo-1534234828569-2c75a40733d0?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Pesca', 'Tranquilidad', 'Mariscos'],
    travelTips: ['Compra camarón', 'Playa solitaria', 'Vida local'],
    category: 'Cultura',
    rating: 4.3
  },
  {
    id: 'c_playa_escondida',
    name: 'Playa Escondida',
    location: 'Esmeraldas',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'Reserva ecológica privada.',
    fullDescription: 'Santuario de naturaleza con playa, bosque y túneles naturales.',
    imageUrl: 'https://images.unsplash.com/photo-1471922694854-ff1b63b20054?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Naturaleza', 'Camping', 'Túneles'],
    travelTips: ['Paga entrada', 'Camping seguro', 'Naturismo opcional'],
    category: 'Naturaleza',
    rating: 4.6
  },
  {
    id: 'c_muisne',
    name: 'Isla de Muisne',
    location: 'Muisne',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'La isla del encanto.',
    fullDescription: 'Isla rodeada de manglares con playas vírgenes y palmeras.',
    imageUrl: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Manglares', 'Playa virgen', 'Tricimotos'],
    travelTips: ['Cruza en bote', 'Paseo en manglar', 'Playa inmensa'],
    category: 'Naturaleza',
    rating: 4.4
  },
  {
    id: 'c_majahual',
    name: 'Majagual',
    location: 'Eloy Alfaro',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'Los manglares más altos del mundo.',
    fullDescription: 'Reserva ecológica Cayapas-Mataje con manglares gigantes.',
    imageUrl: 'https://images.unsplash.com/photo-1543152042-429380798eb3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Manglares gigantes', 'Canoa', 'Selva'],
    travelTips: ['Lleva repelente', 'Guía local', 'Naturaleza pura'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 'c_portete',
    name: 'Isla Portete',
    location: 'Mompiche',
    region: 'Costa',
    province: 'Esmeraldas',
    description: 'Isla de palmeras caribeñas.',
    fullDescription: 'Pequeña isla frente a Mompiche con cientos de palmeras y agua tranquila.',
    imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Palmeras', 'Relax', 'Cruce corto'],
    travelTips: ['Cruza en bote', 'Picnic', 'Fotos increíbles'],
    category: 'Playa',
    rating: 4.7
  },

  // --- GUAYAS ---
  {
    id: 'c_guayaquil',
    name: 'Malecón 2000',
    location: 'Guayaquil',
    region: 'Costa',
    province: 'Guayas',
    description: 'Icono de la Perla del Pacífico.',
    fullDescription: '2.5km de jardines, historia y modernidad junto al río Guayas.',
    imageUrl: 'https://images.unsplash.com/photo-1575487428448-4770e0a53b53?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['La Perla', 'La Rotonda', 'Jardines'],
    travelTips: ['Ve al atardecer', 'Sube la rueda', 'Seguridad'],
    category: 'Cultura',
    rating: 4.8
  },
  {
    id: 'c_las_penas',
    name: 'Barrio Las Peñas',
    location: 'Guayaquil',
    region: 'Costa',
    province: 'Guayas',
    description: 'El barrio donde nació la ciudad.',
    fullDescription: 'Casas patrimoniales coloridas y 444 escalones hasta el faro.',
    imageUrl: 'https://images.unsplash.com/photo-1626922765383-a7b629002271?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Faro', 'Escalinatas', 'Arte'],
    travelTips: ['Sube al faro', 'Galerías arte', 'Vista panorámica'],
    category: 'Cultura',
    rating: 4.8
  },
  {
    id: 'c_santay',
    name: 'Isla Santay',
    location: 'Durán',
    region: 'Costa',
    province: 'Guayas',
    description: 'Pulmón verde en el río.',
    fullDescription: 'Humedal protegido con cocodrileras y eco-aldea. Acceso por puente peatonal.',
    imageUrl: 'https://images.unsplash.com/photo-1544662660-39878297b7cb?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cocodrilos', 'Caminata', 'Bicicleta'],
    travelTips: ['Alquila bici', 'Lleva agua', 'Cruza el puente'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 'c_parque_historico',
    name: 'Parque Histórico',
    location: 'Samborondón',
    region: 'Costa',
    province: 'Guayas',
    description: 'Historia y vida silvestre.',
    fullDescription: 'Recreación del Guayaquil antiguo y zoológico de fauna local inmersivo.',
    imageUrl: 'https://images.unsplash.com/photo-1594895079496-6b22c7a36a79?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Animales', 'Casas antiguas', 'Teatro'],
    travelTips: ['Gratis', 'Show en vivo', 'Ideal familias'],
    category: 'Cultura',
    rating: 4.9
  },
  {
    id: 'c_bucay',
    name: 'Cascadas de Bucay',
    location: 'Bucay',
    region: 'Costa',
    province: 'Guayas',
    description: 'Aventura al límite con la sierra.',
    fullDescription: 'Bosque nublado lleno de cascadas para hacer canyoning y senderismo.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Canyoning', 'Cascadas', 'Trapiche'],
    travelTips: ['Mójate', 'Tour 4x4', 'Jugo de caña'],
    category: 'Aventura',
    rating: 4.7
  },
  {
    id: 'c_churute',
    name: 'Manglares Churute',
    location: 'Naranjal',
    region: 'Costa',
    province: 'Guayas',
    description: 'Reserva de manglares y monos.',
    fullDescription: 'Estuario protegido. Paseos en canoa y sendero de monos aulladores.',
    imageUrl: 'https://images.unsplash.com/photo-1543152042-429380798eb3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Manglar', 'Monos', 'Cacao'],
    travelTips: ['Repelente', 'Tour canoa', 'Cangrejo en Naranjal'],
    category: 'Naturaleza',
    rating: 4.6
  },
  {
    id: 'c_el_morro',
    name: 'Puerto El Morro',
    location: 'Guayaquil',
    region: 'Costa',
    province: 'Guayas',
    description: 'Delfines y manglares.',
    fullDescription: 'Pueblo tradicional desde donde salen lanchas para ver delfines nariz de botella.',
    imageUrl: 'https://images.unsplash.com/photo-1516972087532-6b9409b67323?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Delfines', 'Garzas', 'Estero'],
    travelTips: ['Lleva gorra', 'Paseo lancha', 'Come liza asada'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 'c_varadero',
    name: 'Playa Varadero',
    location: 'Posorja',
    region: 'Costa',
    province: 'Guayas',
    description: 'Patio de comidas frente al mar.',
    fullDescription: 'Playa amplia con excelente infraestructura gastronómica.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Comida', 'Playa amplia', 'Atardecer'],
    travelTips: ['Come mariscos', 'Fácil acceso', 'Familiar'],
    category: 'Gastronomía',
    rating: 4.3
  },
  {
    id: 'c_cerro_blanco',
    name: 'Bosque Cerro Blanco',
    location: 'Guayaquil',
    region: 'Costa',
    province: 'Guayas',
    description: 'Bosque seco tropical.',
    fullDescription: 'Reserva privada a las afueras de Guayaquil. Senderismo y avistamiento de aves.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Senderos', 'Guacamayos', 'Bosque'],
    travelTips: ['Reserva antes', 'Guía obligatorio', 'Camping'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 'c_puná',
    name: 'Isla Puná',
    location: 'Guayaquil',
    region: 'Costa',
    province: 'Guayas',
    description: 'La isla grande del Golfo.',
    fullDescription: 'Isla histórica y natural. Playas tranquilas y delfines en el cruce.',
    imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Playa Cauchiche', 'Delfines', 'Historia'],
    travelTips: ['Cruce en lancha', 'Turismo comunitario', 'Relax'],
    category: 'Aventura',
    rating: 4.2
  },

  // --- EL ORO ---
  {
    id: 'c_jambeli',
    name: 'Archipiélago de Jambelí',
    location: 'Machala',
    region: 'Costa',
    province: 'El Oro',
    description: 'Islas y manglares orenses.',
    fullDescription: 'Conjunto de islas con playas cálidas accesibles desde Puerto Bolívar.',
    imageUrl: 'https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Playa', 'Mariscos', 'Lancha'],
    travelTips: ['Sal de Puerto Bolívar', 'Come mariscos', 'Regresa temprano'],
    category: 'Playa',
    rating: 4.4
  },
  {
    id: 'c_zaruma',
    name: 'Zaruma',
    location: 'Zaruma',
    region: 'Costa',
    province: 'El Oro',
    description: 'Patrimonio de madera y oro.',
    fullDescription: 'Ciudad mágica en la montaña con casas de madera, café y minas de oro.',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Arquitectura', 'Mina Sexmo', 'Tigrillo'],
    travelTips: ['Entra a la mina', 'Prueba tigrillo', 'Compra café'],
    category: 'Cultura',
    rating: 4.9
  },
  {
    id: 'c_puyango',
    name: 'Bosque Petrificado Puyango',
    location: 'Las Lajas',
    region: 'Costa',
    province: 'El Oro',
    description: 'Árboles de piedra milenarios.',
    fullDescription: 'Yacimiento de fósiles marinos y madera petrificada más grande del país.',
    imageUrl: 'https://images.unsplash.com/photo-1518117622676-47a3246eb796?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Troncos petrificados', 'Museo', 'Senderos'],
    travelTips: ['Lleva agua', 'Mucho calor', 'Guía local'],
    category: 'Cultura',
    rating: 4.6
  },
  {
    id: 'c_hilario',
    name: 'Puerto Jelí',
    location: 'Santa Rosa',
    region: 'Costa',
    province: 'El Oro',
    description: 'Capital gastronómica del sur.',
    fullDescription: 'Famoso por ofrecer los mejores mariscos, especialmente conchas y cangrejos.',
    imageUrl: 'https://images.unsplash.com/photo-1569430349603-60b6c8f9c738?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Gastronomía', 'Conchas asadas', 'Manglar'],
    travelTips: ['Ve con hambre', 'Pide paila marina', 'Familiar'],
    category: 'Gastronomía',
    rating: 4.8
  },
  {
    id: 'c_piñas',
    name: 'Piñas',
    location: 'Piñas',
    region: 'Costa',
    province: 'El Oro',
    description: 'Ciudad de las orquídeas.',
    fullDescription: 'Rodeada de montañas y neblina, famosa por su colección de orquídeas.',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Orquideario', 'Mirador', 'Naturaleza'],
    travelTips: ['Visita reserva', 'Clima fresco', 'Fotos flores'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 'c_balsas',
    name: 'Balsas',
    location: 'Balsas',
    region: 'Costa',
    province: 'El Oro',
    description: 'Valle verde productivo.',
    fullDescription: 'Zona agrícola paisajística entre la costa y la sierra.',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Paisaje', 'Agricultura', 'Paz'],
    travelTips: ['Paso a Loja', 'Compra fruta', 'Vistas'],
    category: 'Naturaleza',
    rating: 4.2
  },
  {
    id: 'c_hilarión',
    name: 'Reserva Buenaventura',
    location: 'Piñas',
    region: 'Costa',
    province: 'El Oro',
    description: 'Colibríes y pericos.',
    fullDescription: 'Reserva de la Fundación Jocotoco. Lugar top para aviturismo.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Colibríes', 'Perico de Orcés', 'Senderos'],
    travelTips: ['Lleva binoculares', 'Reserva lodge', 'Silencio'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 'c_isla_santa_clara',
    name: 'Isla Santa Clara',
    location: 'Puerto Bolívar',
    region: 'Costa',
    province: 'El Oro',
    description: 'La isla del muerto.',
    fullDescription: 'Refugio de vida silvestre marina. Aves fragatas y lobos marinos.',
    imageUrl: 'https://images.unsplash.com/photo-1589391090333-e77373809b02?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Aves marinas', 'Delfines', 'Historia'],
    travelTips: ['Tour lancha', 'No desembarque', 'Fotos'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 'c_arenillas',
    name: 'Reserva Ecológica Arenillas',
    location: 'Arenillas',
    region: 'Costa',
    province: 'El Oro',
    description: 'Bosque seco fronterizo.',
    fullDescription: 'Protege el bosque seco tumbesino. Gran diversidad de aves endémicas.',
    imageUrl: 'https://images.unsplash.com/photo-1518117622676-47a3246eb796?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Bosque seco', 'Aves', 'Venados'],
    travelTips: ['Permiso previo', 'Calor intenso', 'Aviturismo'],
    category: 'Naturaleza',
    rating: 4.3
  },
  {
    id: 'c_machala',
    name: 'Machala',
    location: 'Machala',
    region: 'Costa',
    province: 'El Oro',
    description: 'Capital bananera del mundo.',
    fullDescription: 'Ciudad comercial con parques renovados y gran gastronomía.',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Parque Juan Montalvo', 'Catedral', 'Bananos'],
    travelTips: ['Feria del Banano', 'Calor', 'Paso a Perú'],
    category: 'Cultura',
    rating: 4.2
  },

  // --- LOS RÍOS ---
  {
    id: 'c_vinces',
    name: 'Vinces',
    location: 'Vinces',
    region: 'Costa',
    province: 'Los Ríos',
    description: 'París Chiquito.',
    fullDescription: 'Famosa por su Torre Eiffel y legado cacaotero del Gran Cacao.',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Torre Eiffel', 'Humedales', 'Cacao'],
    travelTips: ['Regatas en marzo', 'Sube la torre', 'Prueba bollos'],
    category: 'Cultura',
    rating: 4.4
  },
  {
    id: 'c_babahoyo',
    name: 'Casa de Olmedo',
    location: 'Babahoyo',
    region: 'Costa',
    province: 'Los Ríos',
    description: 'Hacienda histórica.',
    fullDescription: 'La Virginia, donde vivió José Joaquín de Olmedo. Historia política y literaria.',
    imageUrl: 'https://images.unsplash.com/photo-1594895079496-6b22c7a36a79?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Museo', 'Río', 'Historia'],
    travelTips: ['Visita guiada', 'Paseo río', 'Cultura'],
    category: 'Cultura',
    rating: 4.3
  },
  {
    id: 'c_abras_mantequilla',
    name: 'Humedal Abras de Mantequilla',
    location: 'Vinces',
    region: 'Costa',
    province: 'Los Ríos',
    description: 'Sitio Ramsar de biodiversidad.',
    fullDescription: 'Sistema de lagunas hogar de cientos de aves acuáticas y monos.',
    imageUrl: 'https://images.unsplash.com/photo-1544662660-39878297b7cb?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Aves', 'Monos', 'Canoa'],
    travelTips: ['Alquila bote', 'Binoculares', 'Naturaleza'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 'c_quevedo',
    name: 'Quevedo - Ruta del Río',
    location: 'Quevedo',
    region: 'Costa',
    province: 'Los Ríos',
    description: 'La ciudad del río.',
    fullDescription: 'Parque lineal y zonas de recreación junto al río Quevedo.',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Malecón', 'Comida', 'Diversión'],
    travelTips: ['Paseo familiar', 'Noche', 'Clima cálido'],
    category: 'Cultura',
    rating: 4.2
  },
  {
    id: 'c_hacienda_cacao',
    name: 'Ruta del Cacao',
    location: 'Vinces/Babahoyo',
    region: 'Costa',
    province: 'Los Ríos',
    description: 'El mejor chocolate del mundo.',
    fullDescription: 'Visita haciendas cacaoteras tradicionales y aprende el proceso del Cacao Arriba.',
    imageUrl: 'https://images.unsplash.com/photo-1621255562094-04d7326a0b94?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Degustación', 'Plantaciones', 'Historia'],
    travelTips: ['Reserva tour', 'Compra chocolate', 'Aprende'],
    category: 'Gastronomía',
    rating: 4.8
  },

  // --- SANTO DOMINGO ---
  {
    id: 'c_tsachila',
    name: 'Comunidad Tsáchila',
    location: 'Santo Domingo',
    region: 'Costa',
    province: 'Santo Domingo',
    description: 'Cultura de los Colorados.',
    fullDescription: 'Museos etnográficos vivos donde conocer la medicina, música y tradiciones Tsáchilas.',
    imageUrl: 'https://images.unsplash.com/photo-1629237302797-17792723c346?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Achiote', 'Marimba', 'Shamanismo'],
    travelTips: ['Limpia energética', 'Compra artesanía', 'Respeto'],
    category: 'Cultura',
    rating: 4.7
  },
  {
    id: 'c_bomboli',
    name: 'Cerro Bombolí',
    location: 'Santo Domingo',
    region: 'Costa',
    province: 'Santo Domingo',
    description: 'Mirador de la ciudad.',
    fullDescription: 'Reserva natural en la ciudad con iglesia y vista panorámica.',
    imageUrl: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Vista', 'Iglesia', 'Naturaleza'],
    travelTips: ['Sube en auto', 'Atardecer', 'Familiar'],
    category: 'Naturaleza',
    rating: 4.3
  },
  {
    id: 'c_alluriquin',
    name: 'Alluriquín',
    location: 'Santo Domingo',
    region: 'Costa',
    province: 'Santo Domingo',
    description: 'Tierra de la melcocha.',
    fullDescription: 'Parada obligatoria para probar los dulces tradicionales hechos de caña.',
    imageUrl: 'https://images.unsplash.com/photo-1528696892704-5e1122852276?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Melcochas', 'Dulces', 'Río'],
    travelTips: ['Compra dulces', 'Paso a la sierra', 'Tradición'],
    category: 'Gastronomía',
    rating: 4.5
  },
  {
    id: 'c_valle_hermoso',
    name: 'Valle Hermoso',
    location: 'Santo Domingo',
    region: 'Costa',
    province: 'Santo Domingo',
    description: 'Rafting y naturaleza.',
    fullDescription: 'Destino de aventura con ríos rápidos y cascadas.',
    imageUrl: 'https://images.unsplash.com/photo-1596423736569-421f28b525f6?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Rafting', 'Cascadas', 'Balnearios'],
    travelTips: ['Deporte extremo', 'Ropa agua', 'Fin de semana'],
    category: 'Aventura',
    rating: 4.6
  },
  {
    id: 'c_la_perla',
    name: 'Bosque Protector La Perla',
    location: 'La Concordia',
    region: 'Costa',
    province: 'Santo Domingo',
    description: 'Selva del Chocó.',
    fullDescription: 'Uno de los últimos remanentes de bosque húmedo del occidente.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Flora', 'Fauna', 'Sendero'],
    travelTips: ['Guía privado', 'Botas', 'Naturaleza'],
    category: 'Naturaleza',
    rating: 4.7
  },

  // ==========================================
  // REGIÓN SIERRA
  // ==========================================

  // --- PICHINCHA ---
  {
    id: 's_quito_centro',
    name: 'Centro Histórico de Quito',
    location: 'Quito',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Patrimonio de la Humanidad.',
    fullDescription: 'El casco colonial mejor conservado. Iglesias de oro, plazas y museos.',
    imageUrl: 'https://images.unsplash.com/photo-1573147895475-1044342337dd?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['La Compañía', 'Plaza Grande', 'El Panecillo'],
    travelTips: ['Cuida tus cosas', 'Visita cúpulas', 'Come hornado'],
    category: 'Cultura',
    rating: 4.9
  },
  {
    id: 's_mitad_mundo',
    name: 'Ciudad Mitad del Mundo',
    location: 'Quito',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Latitud 0°0\'0".',
    fullDescription: 'Monumento a la línea ecuatorial y museos interactivos.',
    imageUrl: 'https://images.unsplash.com/photo-1605218427368-35b86d9a978f?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Monumento', 'Museo Intiñan', 'Huevo'],
    travelTips: ['Ve al Intiñan', 'Lleva gorra', 'Foto clásica'],
    category: 'Cultura',
    rating: 4.6
  },
  {
    id: 's_teleferico',
    name: 'Teleférico de Quito',
    location: 'Quito',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Quito desde el cielo.',
    fullDescription: 'Sube a 4000m en minutos. Vista espectacular de la ciudad y los volcanes.',
    imageUrl: 'https://images.unsplash.com/photo-1542662565-7e4b66b5adaa?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Vista', 'Columpio', 'Ruco Pichincha'],
    travelTips: ['Lleva abrigo', 'Sube temprano (mañana)', 'Caminata'],
    category: 'Aventura',
    rating: 4.7
  },
  {
    id: 's_mindo',
    name: 'Mindo',
    location: 'Mindo',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Bosque nublado y aves.',
    fullDescription: 'Paraíso de biodiversidad. Mariposas, colibríes, cascadas y canopy.',
    imageUrl: 'https://images.unsplash.com/photo-1550942007-6a4a40776b05?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Tarabita', 'Cascadas', 'Mariposario'],
    travelTips: ['Canopy', 'Tour chocolate', 'Repelente'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 's_cayambe',
    name: 'Volcán Cayambe',
    location: 'Cayambe',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Nieve y bizcochos.',
    fullDescription: 'Tercera montaña más alta. Glaciares impresionantes y comida tradicional.',
    imageUrl: 'https://images.unsplash.com/photo-1542665093-a4e92b3c4850?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Refugio', 'Nieve', 'Bizcochos'],
    travelTips: ['Ropa térmica', 'Prueba bizcochos', 'Altura'],
    category: 'Montaña',
    rating: 4.7
  },
  {
    id: 's_antisana',
    name: 'Reserva Antisana',
    location: 'Pichincha',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Tierra del cóndor.',
    fullDescription: 'Páramo espectacular ideal para ver cóndores y la laguna de La Mica.',
    imageUrl: 'https://images.unsplash.com/photo-1547995886-671239c4a036?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cóndores', 'Laguna Mica', 'Volcán'],
    travelTips: ['Frío intenso', 'Binoculares', 'Permiso auto'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 's_ilalo',
    name: 'Volcán Ilaló',
    location: 'Tumbaco',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Mirador de los valles.',
    fullDescription: 'Volcán inactivo ideal para trekking suave cerca de la ciudad.',
    imageUrl: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cruz', 'Senderismo', 'Vista 360'],
    travelTips: ['Lleva agua', 'Zapatos cómodos', 'Mañana'],
    category: 'Montaña',
    rating: 4.5
  },
  {
    id: 's_pululahua',
    name: 'Reserva Geobotánica Pululahua',
    location: 'Quito',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Cráter habitado.',
    fullDescription: 'Un volcán inactivo con una comunidad agrícola viviendo en su caldera.',
    imageUrl: 'https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Mirador', 'Cráter', 'Senderos'],
    travelTips: ['Baja caminando', 'Sube en auto', 'Clima cambiante'],
    category: 'Naturaleza',
    rating: 4.6
  },
  {
    id: 's_pahuma',
    name: 'Reserva Orquideológica El Pahuma',
    location: 'Nanegalito',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Santuario de orquídeas.',
    fullDescription: 'Bosque nublado lleno de orquídeas silvestres y cascadas.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Orquídeas', 'Cascadas', 'Senderos'],
    travelTips: ['Lluvia probable', 'Cámara macro', 'Sendero fácil'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 's_guayllabamba',
    name: 'Zoológico de Guayllabamba',
    location: 'Guayllabamba',
    region: 'Sierra',
    province: 'Pichincha',
    description: 'Refugio de fauna andina.',
    fullDescription: 'El zoológico más importante de Quito, enfocado en especies nativas.',
    imageUrl: 'https://images.unsplash.com/photo-1547995886-671239c4a036?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Osos de anteojos', 'Cóndores', 'Locro'],
    travelTips: ['Come locro', 'Ideal niños', 'Clima cálido'],
    category: 'Cultura',
    rating: 4.4
  },

  // --- COTOPAXI ---
  {
    id: 's_cotopaxi',
    name: 'Parque Nacional Cotopaxi',
    location: 'Latacunga',
    region: 'Sierra',
    province: 'Cotopaxi',
    description: 'El coloso de los Andes.',
    fullDescription: 'Volcán activo icónico. Paisajes de páramo, caballos salvajes y nieve.',
    imageUrl: 'https://images.unsplash.com/photo-1563297129-37803e726488?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Volcán', 'Laguna Limpiopungo', 'Refugio'],
    travelTips: ['Ropa invierno', 'Té de coca', 'Auto alto'],
    category: 'Montaña',
    rating: 4.9
  },
  {
    id: 's_quilotoa',
    name: 'Laguna del Quilotoa',
    location: 'Pujilí',
    region: 'Sierra',
    province: 'Cotopaxi',
    description: 'La esmeralda de los Andes.',
    fullDescription: 'Laguna turquesa en el cráter de un volcán. Paisaje impresionante.',
    imageUrl: 'https://images.unsplash.com/photo-1518182170546-0766aaab9aa4?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Laguna', 'Kayak', 'Mirador'],
    travelTips: ['Bajada fácil', 'Subida dura (mulas)', 'Viento'],
    category: 'Aventura',
    rating: 4.9
  },
  {
    id: 's_illinizas',
    name: 'Reserva Ecológica Los Ilinizas',
    location: 'Mejía',
    region: 'Sierra',
    province: 'Cotopaxi',
    description: 'Picos gemelos.',
    fullDescription: 'Iliniza Norte (roca) e Iliniza Sur (nieve). Reto para montañistas.',
    imageUrl: 'https://images.unsplash.com/photo-1610731674753-938382729a6e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Montañismo', 'Paisaje', 'Laguna Verde'],
    travelTips: ['Guía experto', 'Equipo montaña', 'Aclimatación'],
    category: 'Montaña',
    rating: 4.7
  },
  {
    id: 's_la_mana',
    name: 'Cascadas de La Maná',
    location: 'La Maná',
    region: 'Sierra',
    province: 'Cotopaxi',
    description: 'Tesoro subtropical.',
    fullDescription: 'Zona cálida de Cotopaxi con cascadas y cuevas.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cascadas', 'Cueva de los Murciélagos', 'Clima'],
    travelTips: ['Ropa ligera', 'Nadar', 'Relajarse'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 's_pujili',
    name: 'Pujilí',
    location: 'Pujilí',
    region: 'Sierra',
    province: 'Cotopaxi',
    description: 'Cultura del Danzante.',
    fullDescription: 'Pueblo famoso por su fiesta de Corpus Christi y el Danzante de Pujilí.',
    imageUrl: 'https://images.unsplash.com/photo-1621255562094-04d7326a0b94?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Danzante', 'Mercado', 'Cerámica'],
    travelTips: ['Visita en Corpus', 'Compra artesanía', 'Frío'],
    category: 'Cultura',
    rating: 4.4
  },

  // --- IMBABURA ---
  {
    id: 's_otavalo',
    name: 'Mercado de Otavalo',
    location: 'Otavalo',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'Mercado indígena mundial.',
    fullDescription: 'Plaza de los Ponchos, textiles, colores y cultura Kichwa.',
    imageUrl: 'https://images.unsplash.com/photo-1531773200780-6060c490a606?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Artesanías', 'Ponchos', 'Cultura'],
    travelTips: ['Regatea', 'Ve sábado', 'Textiles'],
    category: 'Cultura',
    rating: 4.8
  },
  {
    id: 's_cuicocha',
    name: 'Laguna de Cuicocha',
    location: 'Cotacachi',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'Laguna de los dioses.',
    fullDescription: 'Cráter volcánico con dos islotes. Paseo en lancha y sendero.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Lancha', 'Islotes', 'Sendero'],
    travelTips: ['Chaqueta viento', 'Paseo bote', 'Carne colorada'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 's_peguche',
    name: 'Cascada de Peguche',
    location: 'Otavalo',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'Sitio sagrado Kichwa.',
    fullDescription: 'Cascada ceremonial rodeada de bosque de eucaliptos.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cascada', 'Bosque', 'Rituales'],
    travelTips: ['Caminata fácil', 'Baño ritual', 'Artesanías'],
    category: 'Cultura',
    rating: 4.6
  },
  {
    id: 's_yahuarcocha',
    name: 'Laguna de Yahuarcocha',
    location: 'Ibarra',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'Laguna histórica.',
    fullDescription: 'Laguna con pista de carreras. Paseos en bote y pescado frito.',
    imageUrl: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Tilapia', 'Autódromo', 'Bote'],
    travelTips: ['Come pescado', 'Paseo tarde', 'Vista'],
    category: 'Gastronomía',
    rating: 4.5
  },
  {
    id: 's_mojanda',
    name: 'Lagunas de Mojanda',
    location: 'Otavalo',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'Páramo virgen.',
    fullDescription: 'Tres lagunas de altura rodeadas de picos como el Fuya Fuya.',
    imageUrl: 'https://images.unsplash.com/photo-1564757303022-297d2a704e6d?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Laguna Grande', 'Fuya Fuya', 'Páramo'],
    travelTips: ['Muy frío', 'Auto alto', 'Camping'],
    category: 'Aventura',
    rating: 4.7
  },
  {
    id: 's_san_pablo',
    name: 'Lago San Pablo',
    location: 'Otavalo',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'El lago vigilado por el Imbabura.',
    fullDescription: 'Lago extenso al pie del volcán Imbabura. Deportes acuáticos.',
    imageUrl: 'https://images.unsplash.com/photo-1596726693893-6e3e4a2c91a3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Muelle', 'Imbabura', 'Deportes'],
    travelTips: ['Paseo lancha', 'Almuerzo vista', 'Fritada'],
    category: 'Naturaleza',
    rating: 4.6
  },
  {
    id: 's_chota',
    name: 'Valle del Chota',
    location: 'Ibarra',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'Cultura afroecuatoriana.',
    fullDescription: 'Valle cálido seco, hogar de la cultura afrochoteña y la Bomba.',
    imageUrl: 'https://images.unsplash.com/photo-1528696892704-5e1122852276?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Música Bomba', 'Clima', 'Guandul'],
    travelTips: ['Baila bomba', 'Prueba guandul', 'Calor'],
    category: 'Cultura',
    rating: 4.5
  },
  {
    id: 's_cotacachi',
    name: 'Cotacachi',
    location: 'Cotacachi',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'Ciudad del cuero.',
    fullDescription: 'Pueblo famoso por sus artesanías en cuero de alta calidad.',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cuero', 'Calles limpias', 'Carne colorada'],
    travelTips: ['Compra casacas', 'Come carne colorada', 'Pasea'],
    category: 'Cultura',
    rating: 4.6
  },
  {
    id: 's_zuleta',
    name: 'Comuna Zuleta',
    location: 'Ibarra',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'Bordados y quesos.',
    fullDescription: 'Comunidad famosa por sus bordados a mano y haciendas.',
    imageUrl: 'https://images.unsplash.com/photo-1629237302797-17792723c346?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Bordados', 'Quesos', 'Hacienda'],
    travelTips: ['Compra bordados', 'Prueba quesos', 'Paisaje'],
    category: 'Cultura',
    rating: 4.7
  },
  {
    id: 's_intag',
    name: 'Valle de Íntag',
    location: 'Cotacachi',
    region: 'Sierra',
    province: 'Imbabura',
    description: 'Café y termas.',
    fullDescription: 'Valle subtropical famoso por su café orgánico y aguas termales.',
    imageUrl: 'https://images.unsplash.com/photo-1544985392-7208e06f9d39?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Café', 'Termas', 'Naturaleza'],
    travelTips: ['Tour café', 'Báñate termas', 'Relájate'],
    category: 'Naturaleza',
    rating: 4.6
  },

  // --- TUNGURAHUA ---
  {
    id: 's_banos',
    name: 'Baños de Agua Santa',
    location: 'Baños',
    region: 'Sierra',
    province: 'Tungurahua',
    description: 'Aventura y cascadas.',
    fullDescription: 'Destino top de aventura. Cascadas, rafting, columpios y termas.',
    imageUrl: 'https://images.unsplash.com/photo-1634657963273-02f693b790d5?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Pailón Diablo', 'Casa Árbol', 'Termas'],
    travelTips: ['Ruta cascadas', 'Melcochas', 'Vida nocturna'],
    category: 'Aventura',
    rating: 4.8
  },
  {
    id: 's_casa_arbol',
    name: 'La Casa del Árbol',
    location: 'Baños',
    region: 'Sierra',
    province: 'Tungurahua',
    description: 'Columpio del fin del mundo.',
    fullDescription: 'Famoso columpio con vista al volcán Tungurahua.',
    imageUrl: 'https://images.unsplash.com/photo-1596727147705-54a7d7501f71?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Columpio', 'Volcán', 'Fotos'],
    travelTips: ['Ve despejado', 'Fotos increíbles', 'Café'],
    category: 'Aventura',
    rating: 4.8
  },
  {
    id: 's_pailon',
    name: 'Pailón del Diablo',
    location: 'Baños',
    region: 'Sierra',
    province: 'Tungurahua',
    description: 'Cascada brutal.',
    fullDescription: 'Una de las cascadas más potentes. Escaleras junto a la caída de agua.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Grieta', 'Puente', 'Cascada'],
    travelTips: ['Impermeable', 'Camina agachado', 'Noche (luces)'],
    category: 'Naturaleza',
    rating: 4.9
  },
  {
    id: 's_ambato',
    name: 'Parque de la Familia',
    location: 'Ambato',
    region: 'Sierra',
    province: 'Tungurahua',
    description: 'Mirador y jardines.',
    fullDescription: 'Gran parque con jardines frutales y vista a la ciudad.',
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Jardines', 'Granja', 'Picnic'],
    travelTips: ['Fines semana', 'Picnic', 'Familiar'],
    category: 'Cultura',
    rating: 4.5
  },
  {
    id: 's_quisapincha',
    name: 'Quisapincha',
    location: 'Ambato',
    region: 'Sierra',
    province: 'Tungurahua',
    description: 'Pueblo del cuero.',
    fullDescription: 'Destino de compras de artículos de cuero a buen precio.',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Chompas', 'Zapatos', 'Vista'],
    travelTips: ['Compra cuero', 'Come gallina', 'Frío'],
    category: 'Cultura',
    rating: 4.4
  },
  {
    id: 's_salasaca',
    name: 'Salasaca',
    location: 'Pelileo',
    region: 'Sierra',
    province: 'Tungurahua',
    description: 'Tapices indígenas.',
    fullDescription: 'Comunidad experta en tejido de tapices de lana.',
    imageUrl: 'https://images.unsplash.com/photo-1621255562094-04d7326a0b94?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Tapices', 'Mercado', 'Cultura'],
    travelTips: ['Compra arte', 'Conoce telares', 'Cultura'],
    category: 'Cultura',
    rating: 4.3
  },

  // --- CHIMBORAZO ---
  {
    id: 's_chimborazo',
    name: 'Volcán Chimborazo',
    location: 'Riobamba',
    region: 'Sierra',
    province: 'Chimborazo',
    description: 'El punto más alto.',
    fullDescription: 'Montaña más alta de Ecuador. Punto más cercano al sol.',
    imageUrl: 'https://images.unsplash.com/photo-1610731674753-938382729a6e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Refugios', 'Vicuñas', 'Nieve'],
    travelTips: ['Altura extrema', 'Abrigo', 'Despacio'],
    category: 'Montaña',
    rating: 4.9
  },
  {
    id: 's_guamote',
    name: 'Mercado de Guamote',
    location: 'Guamote',
    region: 'Sierra',
    province: 'Chimborazo',
    description: 'Mercado auténtico.',
    fullDescription: 'Feria indígena tradicional de los jueves. Muy fotogénica.',
    imageUrl: 'https://images.unsplash.com/photo-1621255562094-04d7326a0b94?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Feria', 'Animales', 'Ponchos'],
    travelTips: ['Ve jueves', 'Respeta fotos', 'Auténtico'],
    category: 'Cultura',
    rating: 4.6
  },
  {
    id: 's_nariz_diablo',
    name: 'Nariz del Diablo',
    location: 'Alausí',
    region: 'Sierra',
    province: 'Chimborazo',
    description: 'Tren difícil.',
    fullDescription: 'Ruta de tren (cuando opera) o mirador de la montaña zigzagueante.',
    imageUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Paisaje', 'Tren', 'Historia'],
    travelTips: ['Verifica tren', 'Mirador', 'Frío'],
    category: 'Cultura',
    rating: 4.7
  },
  {
    id: 's_ozogoche',
    name: 'Lagunas de Ozogoche',
    location: 'Alausí',
    region: 'Sierra',
    province: 'Chimborazo',
    description: 'Misterio andino.',
    fullDescription: 'Complejo lacustre famoso por el "suicidio" de aves migratorias.',
    imageUrl: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Lagunas', 'Aves', 'Pesca'],
    travelTips: ['Lleva comida', 'Frío', 'Camping'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 's_colta',
    name: 'Laguna de Colta',
    location: 'Colta',
    region: 'Sierra',
    province: 'Chimborazo',
    description: 'Primera iglesia.',
    fullDescription: 'Laguna con la iglesia de Balbanera, la primera católica del país.',
    imageUrl: 'https://images.unsplash.com/photo-1596726693893-6e3e4a2c91a3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Iglesia', 'Laguna', 'Totora'],
    travelTips: ['Visita iglesia', 'Paseo bote', 'Foto'],
    category: 'Cultura',
    rating: 4.4
  },
  {
    id: 's_altar',
    name: 'El Altar',
    location: 'Penipe',
    region: 'Sierra',
    province: 'Chimborazo',
    description: 'La catedral de roca.',
    fullDescription: 'Volcán extinto con la Laguna Amarilla en su cráter. Trekking exigente.',
    imageUrl: 'https://images.unsplash.com/photo-1518182170546-0766aaab9aa4?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Laguna Amarilla', 'Trekking', 'Nieve'],
    travelTips: ['Muy difícil', 'Requiere guía', '2-3 días'],
    category: 'Aventura',
    rating: 5.0
  },
  {
    id: 's_palmira',
    name: 'Desierto de Palmira',
    location: 'Guamote',
    region: 'Sierra',
    province: 'Chimborazo',
    description: 'Dunas en los Andes.',
    fullDescription: 'Pequeño desierto de arena rodeado de pinos. Paisaje único.',
    imageUrl: 'https://images.unsplash.com/photo-1502219504825-4c07d391f1b2?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Dunas', 'Pinos', 'Fotos'],
    travelTips: ['Lleva agua', 'Sandboard', 'Viento'],
    category: 'Naturaleza',
    rating: 4.6
  },

  // --- AZUAY ---
  {
    id: 's_cuenca',
    name: 'Cuenca',
    location: 'Cuenca',
    region: 'Sierra',
    province: 'Azuay',
    description: 'Ciudad cultural.',
    fullDescription: 'Ciudad hermosa, limpia, con ríos, catedrales y arquitectura colonial.',
    imageUrl: 'https://images.unsplash.com/photo-1579707282660-f82329241940?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Catedral', 'Turi', 'Barranco'],
    travelTips: ['Camina mucho', 'Come mote', 'Museos'],
    category: 'Cultura',
    rating: 4.9
  },
  {
    id: 's_cajas',
    name: 'Parque Nacional Cajas',
    location: 'Cuenca',
    region: 'Sierra',
    province: 'Azuay',
    description: 'Tierra de lagunas.',
    fullDescription: 'Páramo con cientos de lagunas glaciares. Místico y frío.',
    imageUrl: 'https://images.unsplash.com/photo-1564757303022-297d2a704e6d?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Laguna Toreadora', 'Polylepis', 'Pesca'],
    travelTips: ['Muy frío', 'Llueve siempre', 'Trucha'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 's_gualaceo',
    name: 'Gualaceo',
    location: 'Gualaceo',
    region: 'Sierra',
    province: 'Azuay',
    description: 'Jardín del Azuay.',
    fullDescription: 'Pueblo cálido famoso por su calzado, orquídeas y comida.',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Zapatos', 'Río', 'Mercado'],
    travelTips: ['Compra zapatos', 'Come hornado', 'Pasea'],
    category: 'Cultura',
    rating: 4.5
  },
  {
    id: 's_chordeleg',
    name: 'Chordeleg',
    location: 'Chordeleg',
    region: 'Sierra',
    province: 'Azuay',
    description: 'Tierra de joyas.',
    fullDescription: 'Pueblo famoso por sus joyerías de oro y plata, especialmente filigrana.',
    imageUrl: 'https://images.unsplash.com/photo-1531773200780-6060c490a606?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Joyas', 'Filigrana', 'Parque'],
    travelTips: ['Compra joyas', 'Artesanía', 'Cerca Gualaceo'],
    category: 'Cultura',
    rating: 4.6
  },
  {
    id: 's_giron',
    name: 'El Chorro de Girón',
    location: 'Girón',
    region: 'Sierra',
    province: 'Azuay',
    description: 'Cascada doble gigante.',
    fullDescription: 'Impresionante cascada de dos caídas en un entorno de montaña.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cascada', 'Caminata', 'Mirador'],
    travelTips: ['Sube a la 2da', 'Lleva agua', 'Fotos'],
    category: 'Naturaleza',
    rating: 4.7
  },

  // --- CAÑAR ---
  {
    id: 's_ingapirca',
    name: 'Ruinas de Ingapirca',
    location: 'Cañar',
    region: 'Sierra',
    province: 'Cañar',
    description: 'El Machu Picchu ecuatoriano.',
    fullDescription: 'Complejo arqueológico Inca-Cañari mejor conservado. Templo del Sol.',
    imageUrl: 'https://images.unsplash.com/photo-1599596636774-4b47c0b02773?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Templo Sol', 'Cara Inca', 'Museo'],
    travelTips: ['Hace viento', 'Guía', 'Historia'],
    category: 'Cultura',
    rating: 4.8
  },
  {
    id: 's_cojitambo',
    name: 'Cojitambo',
    location: 'Azogues',
    region: 'Sierra',
    province: 'Cañar',
    description: 'Escalada y arqueología.',
    fullDescription: 'Cerro con ruinas cañaris y paredes de roca perfectas para escalar.',
    imageUrl: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Escalada', 'Ruinas', 'Vista'],
    travelTips: ['Equipo escalada', 'Caminata', 'Vista'],
    category: 'Aventura',
    rating: 4.5
  },
  {
    id: 's_biblian',
    name: 'Santuario de Biblián',
    location: 'Biblián',
    region: 'Sierra',
    province: 'Cañar',
    description: 'Iglesia en la roca.',
    fullDescription: 'Santuario de la Virgen del Rocío incrustado en la montaña.',
    imageUrl: 'https://images.unsplash.com/photo-1548625361-9872e4544075?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Iglesia', 'Vista', 'Peregrinación'],
    travelTips: ['Sube gradas', 'Foto panorámica', 'Fe'],
    category: 'Cultura',
    rating: 4.6
  },

  // --- LOJA ---
  {
    id: 's_vilcabamba',
    name: 'Vilcabamba',
    location: 'Loja',
    region: 'Sierra',
    province: 'Loja',
    description: 'Valle de la longevidad.',
    fullDescription: 'Famoso por el clima y la larga vida de sus habitantes. Relax total.',
    imageUrl: 'https://images.unsplash.com/photo-1596726693893-6e3e4a2c91a3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Mandango', 'Senderos', 'Relax'],
    travelTips: ['Camina', 'Agua pura', 'Spa'],
    category: 'Naturaleza',
    rating: 4.7
  },
  {
    id: 's_podocarpus',
    name: 'Parque Nacional Podocarpus',
    location: 'Loja',
    region: 'Sierra',
    province: 'Loja',
    description: 'Biodiversidad del sur.',
    fullDescription: 'Parque con lagunas y bosques únicos. Transición sierra-amazonía.',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Lagunas', 'Miradores', 'Bosque'],
    travelTips: ['Lluvia', 'Botas', 'Caminata'],
    category: 'Naturaleza',
    rating: 4.7
  },
  {
    id: 's_cisne',
    name: 'El Cisne',
    location: 'Loja',
    region: 'Sierra',
    province: 'Loja',
    description: 'Fe mariana.',
    fullDescription: 'Basílica gótica hogar de la Virgen del Cisne. Centro de peregrinación.',
    imageUrl: 'https://images.unsplash.com/photo-1548625361-9872e4544075?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Basílica', 'Virgen', 'Museo'],
    travelTips: ['Agosto (fiesta)', 'Frío', 'Velas'],
    category: 'Cultura',
    rating: 4.8
  },
  {
    id: 's_loja',
    name: 'Loja Ciudad',
    location: 'Loja',
    region: 'Sierra',
    province: 'Loja',
    description: 'Capital musical.',
    fullDescription: 'Ciudad ordenada, culta y puerta de entrada al sur. Parques bonitos.',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Puerta Ciudad', 'Jipiro', 'Calles'],
    travelTips: ['Visita parques', 'Café lojano', 'Tamales'],
    category: 'Cultura',
    rating: 4.5
  },
  {
    id: 's_puyango_loja',
    name: 'Bosque Petrificado (Lado Loja)',
    location: 'Puyango',
    region: 'Sierra',
    province: 'Loja',
    description: 'Fósiles gigantes.',
    fullDescription: 'Extensión del bosque petrificado compartido con El Oro.',
    imageUrl: 'https://images.unsplash.com/photo-1518117622676-47a3246eb796?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Fósiles', 'Museo', 'Calor'],
    travelTips: ['Agua', 'Protector solar', 'Historia'],
    category: 'Cultura',
    rating: 4.6
  },

  // --- CARCHI ---
  {
    id: 's_tulcan',
    name: 'Cementerio de Tulcán',
    location: 'Tulcán',
    region: 'Sierra',
    province: 'Carchi',
    description: 'Arte en ciprés.',
    fullDescription: 'Famoso por sus esculturas verdes (topiaria). Museo vivo.',
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Esculturas', 'Jardín', 'Arte'],
    travelTips: ['Lleva cámara', 'Frío', 'Silencio'],
    category: 'Cultura',
    rating: 4.8
  },
  {
    id: 's_polylepis',
    name: 'Bosque de Polylepis',
    location: 'El Ángel',
    region: 'Sierra',
    province: 'Carchi',
    description: 'Bosque de papel.',
    fullDescription: 'Reserva El Ángel. Árboles milenarios y frailejones gigantes.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Frailejones', 'Polylepis', 'Lagunas'],
    travelTips: ['Muy frío', 'Lluvia', 'Botas'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 's_gruta_paz',
    name: 'Gruta de la Paz',
    location: 'Montúfar',
    region: 'Sierra',
    province: 'Carchi',
    description: 'Santuario en caverna.',
    fullDescription: 'Iglesia natural dentro de una cueva con estalactitas y río.',
    imageUrl: 'https://images.unsplash.com/photo-1504280506541-176f5b945f34?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cueva', 'Virgen', 'Termas'],
    travelTips: ['Baja gradas', 'Piscinas cerca', 'Fe'],
    category: 'Cultura',
    rating: 4.6
  },
  {
    id: 's_lagunas_verdes',
    name: 'Lagunas Verdes',
    location: 'Chiles',
    region: 'Sierra',
    province: 'Carchi',
    description: 'Aguas esmeralda.',
    fullDescription: 'Lagunas de color verde intenso por el azufre del volcán Chiles.',
    imageUrl: 'https://images.unsplash.com/photo-1564757303022-297d2a704e6d?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Color', 'Volcán Chiles', 'Páramo'],
    travelTips: ['Frontera', 'Frío', 'Foto'],
    category: 'Naturaleza',
    rating: 4.5
  },

  // --- BOLÍVAR ---
  {
    id: 's_salinas_bolivar',
    name: 'Salinas de Guaranda',
    location: 'Guaranda',
    region: 'Sierra',
    province: 'Bolívar',
    description: 'Pueblo solidario.',
    fullDescription: 'Ejemplo de economía comunitaria. Fábricas de queso, chocolate y textiles.',
    imageUrl: 'https://images.unsplash.com/photo-1528696892704-5e1122852276?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Queseras', 'Chocolatera', 'Minas'],
    travelTips: ['Compra todo', 'Frío', 'Historia'],
    category: 'Cultura',
    rating: 4.8
  },
  {
    id: 's_guaranda',
    name: 'Guaranda',
    location: 'Guaranda',
    region: 'Sierra',
    province: 'Bolívar',
    description: 'Ciudad de las 7 colinas.',
    fullDescription: 'Capital del carnaval. Casco colonial tranquilo.',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Carnaval', 'Indio Guaranga', 'Parque'],
    travelTips: ['Carnaval (Feb)', 'Pájaro azul', 'Frío'],
    category: 'Cultura',
    rating: 4.4
  },

  // ==========================================
  // REGIÓN AMAZONÍA
  // ==========================================

  // --- NAPO ---
  {
    id: 'a_misahualli',
    name: 'Puerto Misahuallí',
    location: 'Tena',
    region: 'Amazonía',
    province: 'Napo',
    description: 'Playa y monos.',
    fullDescription: 'Puerto turístico con playa de río y monos capuchinos libres.',
    imageUrl: 'https://images.unsplash.com/photo-1544256968-305886af34dc?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Monos', 'Playa', 'Canoa'],
    travelTips: ['Cuida gafas', 'Playa arena', 'Maito'],
    category: 'Selva',
    rating: 4.6
  },
  {
    id: 'a_tena',
    name: 'Tena',
    location: 'Tena',
    region: 'Amazonía',
    province: 'Napo',
    description: 'Capital del rafting.',
    fullDescription: 'Base para aventuras en la selva. Rafting, kayak y cultura.',
    imageUrl: 'https://images.unsplash.com/photo-1596423736569-421f28b525f6?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Rafting', 'Malecón', 'Parque Amazónico'],
    travelTips: ['Haz rafting', 'Guayusa', 'Lluvia'],
    category: 'Aventura',
    rating: 4.8
  },
  {
    id: 'a_papallacta',
    name: 'Termas de Papallacta',
    location: 'Papallacta',
    region: 'Amazonía',
    province: 'Napo',
    description: 'Termas de lujo.',
    fullDescription: 'Aguas termales volcánicas en el páramo, puerta a la Amazonía.',
    imageUrl: 'https://images.unsplash.com/photo-1596489433431-772922638421?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Termas', 'Spa', 'Laguna'],
    travelTips: ['Relájate', 'Frío afuera', 'Trucha'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 'a_jumandy',
    name: 'Cavernas de Jumandy',
    location: 'Archidona',
    region: 'Amazonía',
    province: 'Napo',
    description: 'Laberinto subterráneo.',
    fullDescription: 'Cuevas con río subterráneo y formaciones rocosas.',
    imageUrl: 'https://images.unsplash.com/photo-1504280506541-176f5b945f34?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cueva', 'Río', 'Estalactitas'],
    travelTips: ['Linterna', 'Mojarse', 'Guía'],
    category: 'Aventura',
    rating: 4.7
  },
  {
    id: 'a_laguna_azul',
    name: 'Laguna Azul',
    location: 'Tena',
    region: 'Amazonía',
    province: 'Napo',
    description: 'Piscinas naturales.',
    fullDescription: 'Pozas de agua cristalina formadas por ríos selváticos.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Nadar', 'Paisaje', 'Selva'],
    travelTips: ['Agua fría', 'Fotos', 'Senderos'],
    category: 'Naturaleza',
    rating: 4.6
  },
  {
    id: 'a_hollin',
    name: 'Cascada del Río Hollín',
    location: 'Loreto',
    region: 'Amazonía',
    province: 'Napo',
    description: 'Caudal impresionante.',
    fullDescription: 'Cascada potente junto a la carretera.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cascada', 'Foto', 'Paso'],
    travelTips: ['Para la foto', 'Rocío agua', 'Cuidado'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 'a_pimpilala',
    name: 'Cascadas de Pimpilala',
    location: 'Tena',
    region: 'Amazonía',
    province: 'Napo',
    description: 'Ruta de cascadas.',
    fullDescription: 'Aventura caminando por el río y escalando cascadas.',
    imageUrl: 'https://images.unsplash.com/photo-1546949364-772922638421?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Caminata', 'Agua', 'Aventura'],
    travelTips: ['Zapatos agua', 'Guía', 'Divertido'],
    category: 'Aventura',
    rating: 4.7
  },
  {
    id: 'a_san_rafael',
    name: 'Cascada San Rafael (Ex)',
    location: 'Chaco',
    region: 'Amazonía',
    province: 'Napo',
    description: 'La más alta (histórica).',
    fullDescription: 'Zona paisajística donde estuvo la cascada más alta. Ahora arco de piedra.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Volcán Reventador', 'Paisaje', 'Historia'],
    travelTips: ['Ver cambios', 'Aves', 'Selva alta'],
    category: 'Naturaleza',
    rating: 4.4
  },
  {
    id: 'a_shandia',
    name: 'Comunidad Shandia',
    location: 'Tena',
    region: 'Amazonía',
    province: 'Napo',
    description: 'Turismo comunitario.',
    fullDescription: 'Familia Kichwa, chocolate y río Jatunyacu.',
    imageUrl: 'https://images.unsplash.com/photo-1621255562094-04d7326a0b94?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Chocolate', 'Cultura', 'Río'],
    travelTips: ['Aprende', 'Compra cacao', 'Amable'],
    category: 'Cultura',
    rating: 4.8
  },
  {
    id: 'a_amzoonico',
    name: 'AmaZOOnico',
    location: 'Tena',
    region: 'Amazonía',
    province: 'Napo',
    description: 'Rescate animal.',
    fullDescription: 'Centro de rescate de fauna amazónica accesible por canoa.',
    imageUrl: 'https://images.unsplash.com/photo-1543152042-429380798eb3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Animales', 'Educación', 'Canoa'],
    travelTips: ['Donación', 'No tocar', 'Voluntariado'],
    category: 'Naturaleza',
    rating: 4.7
  },

  // --- PASTAZA ---
  {
    id: 'a_puyo',
    name: 'Puyo',
    location: 'Puyo',
    region: 'Amazonía',
    province: 'Pastaza',
    description: 'Corazón de la Amazonía.',
    fullDescription: 'Ciudad comercial con malecón y parques etnobotánicos.',
    imageUrl: 'https://images.unsplash.com/photo-1596423736569-421f28b525f6?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Paseo río', 'Parque Omaere', 'Artesanías'],
    travelTips: ['Compra balsa', 'Lluvia', 'Museos'],
    category: 'Cultura',
    rating: 4.5
  },
  {
    id: 'a_indichuris',
    name: 'Mirador Indichuris',
    location: 'Puyo',
    region: 'Amazonía',
    province: 'Pastaza',
    description: 'Vista de la selva.',
    fullDescription: 'Mirador famoso por sus hamacas y columpios con vista al río Pastaza.',
    imageUrl: 'https://images.unsplash.com/photo-1544985392-7208e06f9d39?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Vista', 'Columpio', 'Cueva'],
    travelTips: ['Fotos', 'Hamacas', 'Caminata'],
    category: 'Aventura',
    rating: 4.7
  },
  {
    id: 'a_hola_vida',
    name: 'Cascada Hola Vida',
    location: 'Puyo',
    region: 'Amazonía',
    province: 'Pastaza',
    description: 'Cascada familiar.',
    fullDescription: 'Reserva privada con sendero fácil y cascada hermosa.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cascada', 'Sendero', 'Selva'],
    travelTips: ['Báñate', 'Fácil acceso', 'Comida cerca'],
    category: 'Naturaleza',
    rating: 4.6
  },
  {
    id: 'a_fatima',
    name: 'Zoocriadero Fátima',
    location: 'Puyo',
    region: 'Amazonía',
    province: 'Pastaza',
    description: 'Animales y educación.',
    fullDescription: 'Centro de rescate y educación ambiental.',
    imageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Tapir', 'Capibara', 'Serpientes'],
    travelTips: ['Visita rápida', 'Educativo', 'Niños'],
    category: 'Naturaleza',
    rating: 4.4
  },
  {
    id: 'a_sarayaku',
    name: 'Sarayaku',
    location: 'Pastaza',
    region: 'Amazonía',
    province: 'Pastaza',
    description: 'Pueblo del Mediodía.',
    fullDescription: 'Comunidad Kichwa famosa por su defensa de la selva. Acceso aéreo o fluvial.',
    imageUrl: 'https://images.unsplash.com/photo-1621255562094-04d7326a0b94?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cultura', 'Resistencia', 'Selva profunda'],
    travelTips: ['Permiso', 'Avioneta', 'Experiencia única'],
    category: 'Cultura',
    rating: 4.9
  },

  // --- SUCUMBÍOS ---
  {
    id: 'a_cuyabeno',
    name: 'Reserva Cuyabeno',
    location: 'Lago Agrio',
    region: 'Amazonía',
    province: 'Sucumbíos',
    description: 'Lagunas negras.',
    fullDescription: 'El mejor lugar para ver fauna acuática: delfines, caimanes, anacondas.',
    imageUrl: 'https://images.unsplash.com/photo-1627921200830-47402d242491?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Laguna Grande', 'Delfines', 'Atardecer'],
    travelTips: ['Tour 3-4 días', 'Impermeable', 'Nadar laguna'],
    category: 'Selva',
    rating: 4.9
  },
  {
    id: 'a_limoncocha',
    name: 'Laguna de Limoncocha',
    location: 'Shushufindi',
    region: 'Amazonía',
    province: 'Sucumbíos',
    description: 'Reino del caimán negro.',
    fullDescription: 'Laguna biológica llena de caimanes y aves. Tour nocturno recomendado.',
    imageUrl: 'https://images.unsplash.com/photo-1516972087532-6b9409b67323?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Caimanes', 'Pirañas', 'Noche'],
    travelTips: ['Linterna', 'Repelente', 'Silencio'],
    category: 'Selva',
    rating: 4.6
  },
  {
    id: 'a_lago_agrio',
    name: 'Parque Perla',
    location: 'Lago Agrio',
    region: 'Amazonía',
    province: 'Sucumbíos',
    description: 'Parque ecológico urbano.',
    fullDescription: 'Reserva natural dentro de la ciudad con laguna y canopy.',
    imageUrl: 'https://images.unsplash.com/photo-1543152042-429380798eb3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Canopy', 'Laguna', 'Senderos'],
    travelTips: ['Fácil acceso', 'Familiar', 'Deporte'],
    category: 'Aventura',
    rating: 4.3
  },
  {
    id: 'a_panacocha',
    name: 'Pañacocha',
    location: 'Río Napo',
    region: 'Amazonía',
    province: 'Sucumbíos',
    description: 'Laguna remota.',
    fullDescription: 'Laguna de aguas negras hogar de delfines rosados y paiches.',
    imageUrl: 'https://images.unsplash.com/photo-1544662660-39878297b7cb?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Delfines', 'Pesca', 'Selva'],
    travelTips: ['Lancha rápido', 'Lodge', 'Naturaleza'],
    category: 'Selva',
    rating: 4.7
  },

  // --- ORELLANA ---
  {
    id: 'a_yasuni',
    name: 'Parque Nacional Yasuní',
    location: 'Coca',
    region: 'Amazonía',
    province: 'Orellana',
    description: 'Biodiversidad mundial.',
    fullDescription: 'Lugar más biodiverso del planeta. Selva virgen y comunidades Waorani.',
    imageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Saladeros', 'Torres', 'Jaguares'],
    travelTips: ['Vacuna', 'Tour costoso', 'Único'],
    category: 'Selva',
    rating: 5.0
  },
  {
    id: 'a_coca',
    name: 'Museo MACCO',
    location: 'Coca',
    region: 'Amazonía',
    province: 'Orellana',
    description: 'Cultura amazónica.',
    fullDescription: 'Museo arqueológico y centro cultural moderno a orillas del Napo.',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Arqueología', 'Río', 'Arte'],
    travelTips: ['Aire acondicionado', 'Café', 'Historia'],
    category: 'Cultura',
    rating: 4.5
  },
  {
    id: 'a_taracoa',
    name: 'Laguna de Taracoa',
    location: 'Coca',
    region: 'Amazonía',
    province: 'Orellana',
    description: 'Pesca y relax.',
    fullDescription: 'Laguna extensa ideal para pesca deportiva y paseos.',
    imageUrl: 'https://images.unsplash.com/photo-1544662660-39878297b7cb?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Pesca', 'Comida', 'Bote'],
    travelTips: ['Fin de semana', 'Comida típica', 'Relax'],
    category: 'Naturaleza',
    rating: 4.2
  },

  // --- MORONA SANTIAGO ---
  {
    id: 'a_macas',
    name: 'Macas',
    location: 'Macas',
    region: 'Amazonía',
    province: 'Morona Santiago',
    description: 'Esmeralda oriental.',
    fullDescription: 'Ciudad limpia con vista al volcán Sangay y cultura Shuar.',
    imageUrl: 'https://images.unsplash.com/photo-1628080558742-ad42f20d8293?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Catedral', 'Mirador', 'Ayampaco'],
    travelTips: ['Prueba ayampaco', 'Senderismo', 'Clima'],
    category: 'Cultura',
    rating: 4.6
  },
  {
    id: 'a_tayos',
    name: 'Cueva de los Tayos',
    location: 'Limón Indanza',
    region: 'Amazonía',
    province: 'Morona Santiago',
    description: 'Misterio subterráneo.',
    fullDescription: 'Cueva legendaria, profunda y misteriosa. Expedición exigente.',
    imageUrl: 'https://images.unsplash.com/photo-1504280506541-176f5b945f34?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Rappel', 'Formaciones', 'Leyendas'],
    travelTips: ['Expedición 3 días', 'Estado físico', 'Guía Shuar'],
    category: 'Aventura',
    rating: 4.9
  },
  {
    id: 'a_laberintos',
    name: 'Laberintos de Chigüilpe',
    location: 'Macas',
    region: 'Amazonía',
    province: 'Morona Santiago',
    description: 'Pasillos de roca.',
    fullDescription: 'Formaciones geológicas naturales que forman un laberinto en la selva.',
    imageUrl: 'https://images.unsplash.com/photo-1518117622676-47a3246eb796?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Rocas', 'Selva', 'Caminata'],
    travelTips: ['Guía', 'No perderse', 'Fotos'],
    category: 'Aventura',
    rating: 4.5
  },

  // --- ZAMORA CHINCHIPE ---
  {
    id: 'a_zamora',
    name: 'Zamora',
    location: 'Zamora',
    region: 'Amazonía',
    province: 'Zamora Chinchipe',
    description: 'Aves y cascadas.',
    fullDescription: 'Ciudad con reloj gigante, entrada sur al Podocarpus.',
    imageUrl: 'https://images.unsplash.com/photo-1596727147705-54a7d7501f71?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Reloj', 'Malecón', 'Cascadas'],
    travelTips: ['Ancas de rana', 'Podocarpus', 'Clima'],
    category: 'Naturaleza',
    rating: 4.7
  },
  {
    id: 'a_bombuscaro',
    name: 'Río Bombuscaro',
    location: 'Zamora',
    region: 'Amazonía',
    province: 'Zamora Chinchipe',
    description: 'Aguas cristalinas.',
    fullDescription: 'Entrada baja del Parque Podocarpus. Río perfecto para bañarse.',
    imageUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Río', 'Aves', 'Orquídeas'],
    travelTips: ['Agua fría', 'Senderos', 'Picnic'],
    category: 'Naturaleza',
    rating: 4.8
  },
  {
    id: 'a_nangaritza',
    name: 'Alto Nangaritza',
    location: 'Nangaritza',
    region: 'Amazonía',
    province: 'Zamora Chinchipe',
    description: 'Tepuyes ecuatorianos.',
    fullDescription: 'Paisajes únicos de mesetas de piedra caliza y selva virgen.',
    imageUrl: 'https://images.unsplash.com/photo-1518117622676-47a3246eb796?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Laberintos', 'Cueva', 'Río'],
    travelTips: ['Lejano', 'Lancha', 'Increíble'],
    category: 'Aventura',
    rating: 4.9
  },
  {
    id: 'a_mil_ilusiones',
    name: 'Laberinto Mil Ilusiones',
    location: 'Panguintza',
    region: 'Amazonía',
    province: 'Zamora Chinchipe',
    description: 'Rocas gigantes.',
    fullDescription: 'Laberinto natural de rocas gigantes y vegetación.',
    imageUrl: 'https://images.unsplash.com/photo-1599596636774-4b47c0b02773?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Rocas', 'Sendero', 'Fotos'],
    travelTips: ['Guía', 'Caminar', 'Naturaleza'],
    category: 'Aventura',
    rating: 4.6
  },

  // ==========================================
  // REGIÓN INSULAR (GALÁPAGOS)
  // ==========================================
  {
    id: 'i_tortuga_bay',
    name: 'Tortuga Bay',
    location: 'Santa Cruz',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Playa perfecta.',
    fullDescription: 'Arena blanca infinita, iguanas y tiburones en manglar.',
    imageUrl: 'https://images.unsplash.com/photo-1516641396056-0ce60a85d49f?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Iguanas', 'Playa Mansa', 'Tiburones'],
    travelTips: ['Camina 45min', 'Agua', 'No tocar'],
    category: 'Playa',
    rating: 5.0
  },
  {
    id: 'i_kicker_rock',
    name: 'León Dormido',
    location: 'San Cristóbal',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Snorkel profundo.',
    fullDescription: 'Formación rocosa en mar abierto. Tiburones martillo.',
    imageUrl: 'https://images.unsplash.com/photo-1596489397685-6e0a8118029d?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Martillos', 'Tortugas', 'Roca'],
    travelTips: ['Tour barco', 'Corrientes', 'Increíble'],
    category: 'Aventura',
    rating: 5.0
  },
  {
    id: 'i_bartolome',
    name: 'Isla Bartolomé',
    location: 'Galápagos',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Paisaje lunar.',
    fullDescription: 'Vista icónica del pináculo. Pingüinos y paisaje volcánico.',
    imageUrl: 'https://images.unsplash.com/photo-1502219504825-4c07d391f1b2?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Pináculo', 'Pingüinos', 'Escaleras'],
    travelTips: ['Calor', 'Snorkel', 'Foto postal'],
    category: 'Naturaleza',
    rating: 4.9
  },
  {
    id: 'i_tuneles',
    name: 'Los Túneles',
    location: 'Isabela',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Arcos de lava.',
    fullDescription: 'Formaciones de lava sobre el mar llenas de vida.',
    imageUrl: 'https://images.unsplash.com/photo-1622312270830-22c507117188?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Piqueros', 'Caballitos', 'Tortugas'],
    travelTips: ['Mejor tour', 'Snorkel fácil', 'Lava'],
    category: 'Naturaleza',
    rating: 5.0
  },
  {
    id: 'i_rancho',
    name: 'Rancho Primicias',
    location: 'Santa Cruz',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Tortugas gigantes.',
    fullDescription: 'Camina entre tortugas gigantes en libertad y túneles de lava.',
    imageUrl: 'https://images.unsplash.com/photo-1596726693893-6e3e4a2c91a3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Tortugas', 'Túnel lava', 'Botas'],
    travelTips: ['Usa botas', 'Respeta espacio', 'Fotos'],
    category: 'Naturaleza',
    rating: 4.9
  },
  {
    id: 'i_grietas',
    name: 'Las Grietas',
    location: 'Santa Cruz',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Piscina entre rocas.',
    fullDescription: 'Grieta de agua cristalina salobre entre paredes de lava.',
    imageUrl: 'https://images.unsplash.com/photo-1544662660-39878297b7cb?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Nadar', 'Agua clara', 'Peces'],
    travelTips: ['Ve temprano', 'Agua fría', 'Sal'],
    category: 'Aventura',
    rating: 4.7
  },
  {
    id: 'i_loberia',
    name: 'La Lobería',
    location: 'San Cristóbal',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Lobos y surf.',
    fullDescription: 'Playa llena de lobos marinos e iguanas. Olas para surf.',
    imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Lobos', 'Iguanas', 'Surf'],
    travelTips: ['No toques', 'Cuidado machos', 'Atardecer'],
    category: 'Playa',
    rating: 4.8
  },
  {
    id: 'i_tintoreras',
    name: 'Las Tintoreras',
    location: 'Isabela',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Canales de tiburones.',
    fullDescription: 'Islote de lava donde descansan tiburones tintorera.',
    imageUrl: 'https://images.unsplash.com/photo-1589990372204-7667232230a3?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Tiburones', 'Pingüinos', 'Iguanas'],
    travelTips: ['Bote corto', 'Caminata lava', 'Calor'],
    category: 'Naturaleza',
    rating: 4.7
  },
  {
    id: 'i_concha_perla',
    name: 'Concha de Perla',
    location: 'Isabela',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Snorkel en puerto.',
    fullDescription: 'Piscina natural junto al puerto de Villamil llena de vida.',
    imageUrl: 'https://images.unsplash.com/photo-1621376822209-482869927771?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Lobos', 'Rayas', 'Gratis'],
    travelTips: ['Marea alta', 'Máscara', 'Juega con lobos'],
    category: 'Aventura',
    rating: 4.8
  },
  {
    id: 'i_gemelos',
    name: 'Los Gemelos',
    location: 'Santa Cruz',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Cráteres hundidos.',
    fullDescription: 'Dos enormes hundimientos de tierra rodeados de bosque de Scalesia.',
    imageUrl: 'https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Cráteres', 'Bosque', 'Aves'],
    travelTips: ['Lluvia', 'Paso rápido', 'Fotos'],
    category: 'Naturaleza',
    rating: 4.5
  },
  {
    id: 'i_cerro_brujo',
    name: 'Cerro Brujo',
    location: 'San Cristóbal',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Playa de postal.',
    fullDescription: 'Playa de arena blanca con una roca icónica y agua turquesa.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Arena', 'Agua', 'Paisaje'],
    travelTips: ['Tour 360', 'Protector', 'Paraíso'],
    category: 'Playa',
    rating: 4.9
  },
  {
    id: 'i_muro_lagrimas',
    name: 'Muro de las Lágrimas',
    location: 'Isabela',
    region: 'Insular',
    province: 'Galápagos',
    description: 'Historia triste.',
    fullDescription: 'Muro de piedra construido por prisioneros en la antigua colonia penal.',
    imageUrl: 'https://images.unsplash.com/photo-1599596636774-4b47c0b02773?q=80&w=800&auto=format&fit=crop',
    gallery: [],
    highlights: ['Historia', 'Mirador', 'Bicicleta'],
    travelTips: ['Alquila bici', 'Lleva agua', 'Largo camino'],
    category: 'Cultura',
    rating: 4.6
  }
];

export const INITIAL_STORIES: Story[] = [];
export const INITIAL_POSTS: Post[] = [];